services:
  app:
    container_name: banking_transactions_api
    build: .
    command: ["poetry", "run", "uvicorn", "main:get_app", "--host", "0.0.0.0", "--port", "8080"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: banking_transactions_postgres_db
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=banking
      - POSTGRES_PASSWORD=banking
      - POSTGRES_DB=banking
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "public"]
      interval: 5s
      timeout: 5s
      retries: 3