[default]
# Database connection string
DATABASE_DIALECT_DRIVER = "postgresql+psycopg2"
DATABASE_USER = "banking"
DATABASE_PASSWORD = "banking"
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_NAME = "banking"