"""create bank accounts and transactions table

Revision ID: a09e25994399
Revises:
Create Date: 2024-11-01 18:47:56.298396

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a09e25994399"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the sequence
    op.execute(sa.text("CREATE SEQUENCE account_number_seq START 1"))

    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "account_number",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("nextval('account_number_seq')"),
        ),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_number"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bank_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "deposit", "withdraw", "transfer", name="transactionstypes"
            ),
            nullable=False,
        ),
        sa.Column("account_number", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("bank_accounts")

    # Drop the sequence
    op.execute(sa.text("DROP SEQUENCE account_number_seq"))

    # Drop the enum
    op.execute(sa.text("DROP TYPE transactionstypes"))
    # ### end Alembic commands ###
